---

- hosts: localhost
  connection: local
  become: true
  vars:
    repo_url: "{{ repo_url }}"
    dest_dir: "{{ dest_dir }}"


  pre_tasks:
  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: Ensure destination directory exists
    file:
      path: "{{ dest_dir }}"
      state: directory
      mode: '0755'

  tasks:
  - name: install htop, tmux and other packages
    package: 
      name: 
        - htop
        - tmux
        - stow
        - sshfs
  
  - name: Cloning .dotfiles
    become_user: mirec
    ansible.builtin.git:
      repo: "{{ repo_url }}"
      dest: "{{ dest_dir }}"
      recursive: yes
      update: yes
      accept_hostkey: yes
    when: repo_url is defined
    tags:
      - dotfiles

